### PR TITLE
Openapi extend configuration

### PR DESCRIPTION
**Pull request by Trejjam**
This PR provide possibility append Tag to a method [Doc](https://swagger.io/docs/specification/grouping-operations-with-tags/)

### CODE REVIEW

**Comment by f3l1x** [comment]
Wow, nice job. Could give me some example of new annotation? And how does it look in swagger?

**Comment by Trejjam** [comment]
These should be possible: `@Controller\Method("GET", tag="Info")` or `@Controller\Method("GET", tags={"Info", "About"})`.

I will pass a link to Swagger after CI completes its job.

**Comment by f3l1x** [comment]
I see. Looks great. But, we already have @Tag annotation. Which is quite general, you can use it for your own purpose or also for openapi. WDYT?

**Comment by Trejjam** [comment]
For me was the `@Tag` quite confusing. It requires name, but intuitively I do not know what it should be. For some time I was thinking to create `@MethodTag`, but I left this idea for further development.

Maybe make `name` optional?

**Comment by f3l1x** [comment]
Tag name should be required, `@Tag(Info)`, rather make the value optional. Don't you think? Value is usefule when you need to set some internal tag `@Tag(name="resource", value="user/detail")` and then implement it easily on your own security handler.

**Comment by Trejjam** [comment]
Thanks for the hint, it sounds right. Take a look

**Comment by f3l1x** [comment]
Awesome.

**Pull request merged**
