### PR TITLE
Neon loader 

### PR DESCRIPTION
**Pull request by lulco**
This is just minimal prototype for neon loader. If it would be acceptable, I will add other settings (id, tags etc.)

Usage example:

```
parameters:
    schema:
        App\Controllers\HelloController:
            Path: /hello
            Methods:
                index:
                    Method: GET
                    Path: /world

api:
    plugins:
        Apitte\Core\DI\Plugin\CoreSchemaPlugin:
            loader: neon
            schema: %schema%
```

### CODE REVIEW

**Comment by f3l1x** [comment]
Awesome. Could you please add the rest of the schema stuff? I would be 🎉

**Comment by mabar** [comment]
I think it's a good start, you can continue 👍 
Please, at first, prepare complete schema in neon format before writing loader. Just a full example we could talk about.
Implementation itself should be simple (copy of DoctrineAnnotationLoader).

And please, don't send so many fix commits. Use our prepared composer scripts to check code quality. https://github.com/apitte/core/blob/master/composer.json#L52-L70
qa, tester and phpstan should pass.
You could fix almost all codestyle errors with `vendor/bin/codefixer`. Also, we have prepared configuration for phpstorm https://github.com/ninjify/coding-standard/blob/master/phpstorm/contributte.xml

**Comment by lulco** [comment]
OK so full schema should be like this:

```
parameters:
    schema:
        App\Controllers\HelloController:
            Id: id
            Path: /hello
            Methods:
                index:
                    Method: GET
                    # or Methods: [GET, POST]      # both available?              
                    Path: /world
                    Id: methodId
                    Description: method description
                    Tags:
                        tag1: value1
                        tag2: value2
                    Parameters:
                        name1:
                            type: int
                            in: query
                            description: parameter description
                            required: false
                            allowEmpty: false
                            deprecated: false
                        name2:
                            type: scalar
                            in: path
            Tags:
                tag1: value1
                tag2: value2
            GroupIds: [groupId1, groupId2]
            GroupPaths: [groupPath1, groupPath2]

api:
    plugins:
        Apitte\Core\DI\Plugin\CoreSchemaPlugin:
            loader: neon
            schema: %schema%
```

**Comment by lulco** [comment]
Sorry for adding so many fix commits. You just use sooooooo different codestyle like me :) But on the other hand, many commits are no problem, you can just squash commits when you will merge this PR.

I will try to run tests on my local machine first.

**Comment by lulco** [comment]
Is there any problem with full config? https://github.com/apitte/core/pull/50#issuecomment-418529862

**Comment by mabar** [comment]
I am sorry for inactivity.
Please replace PascalCase with camelCase (GroupIds -> groupIds)
Endpoint could have multiple http methods, so `method` -> `methods`
`parameters` -> `requestParameters` to be consistent with annotations.
Rest is ok, I like it 👍 
Please, add also negotiations and let me know if you will run into any problems. Validation is currently divided into schema and annotations itself so you will maybe find something what is not validated properly by schema.

**Comment by f3l1x** [comment]
Any progress @lulco?

**Comment by mabar** [comment]
We made a deal that I will complete this. It need some more complicated changes

**Comment by f3l1x** [comment]
Thanks @lulco

**Pull request merged**
